In [15]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

import plotly.io as pio
pio.renderers.default = "notebook"

filename = "./files/wire_angles.csv"
df = pd.read_csv(filename, skipinitialspace=True, comment="#")

df["num"] = df.index

df[0:20]

#df.describe()

    sector  layer  wire     angle  num
0        1     11     1  0.192901    0
1        1     11     2 -0.092337    1
2        1     11     3 -0.011382    2
3        1     11     4 -0.056829    3
4        1     11     5 -0.053224    4
5        1     11     6 -0.288689    5
6        1     11     7 -0.415443    6
7        1     11     8 -0.314171    7
8        1     11     9  0.187328    8
9        1     11    10  0.139069    9
10       1     11    11 -0.261482   10
11       1     11    12 -0.334744   11
12       1     11    13 -0.188172   12
13       1     11    14 -0.201895   13
14       1     11    15 -0.824545   14
15       1     11    16 -0.820982   15
16       1     11    17 -0.880076   16
17       1     11    18 -0.639343   17
18       1     11    19 -0.379051   18
19       1     11    20 -0.363705   19

In [27]:
fig = px.scatter(df, x ="num", y="angle",
                 color="layer",
                 color_continuous_scale="Viridis")  # optionnel

fig.update_layout(
    title={
        "text": "Angle versus wire angle",
        "x": 0.5,
        "xanchor": "center"

    },
    xaxis_title="wire num",
    yaxis_title="angle (deg)"
)

fig.show()

In [30]:
# df[df["layer"] == 11 ].describe()
df.describe()

       sector       layer        wire       angle         num
count   576.0  576.000000  576.000000  576.000000  576.000000
mean      1.0   34.255208   38.510417   -0.119313  287.500000
std       0.0   11.922320   23.982020    0.212777  166.421153
min       1.0   11.000000    1.000000   -0.913056    0.000000
25%       1.0   22.000000   18.750000   -0.242659  143.750000
50%       1.0   32.000000   36.500000   -0.093791  287.500000
75%       1.0   42.000000   55.250000    0.016988  431.250000
max       1.0   51.000000   99.000000    0.354601  575.000000